---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cms-svc
spec:
  hosts:
  - cms-svc
  http:
  - route:
    - destination:
        host: cms-svc
        subset: v1
---