apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cms-svc # just name for virtualservice
spec:
  hosts:
  - cms-svc.btv-backing.svc.cluster.local # service name to call
  http:
  - route:
    - destination:
        host: cms-svc.btv-backing.svc.cluster.local # service name to call
        subset: v1 # name for subset name
      weight: 80
    - destination:
        host: cms-svc.btv-backing.svc.cluster.local # service name to call
        subset: v2 # name for subset name
      weight: 20