apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cms-svc # just name for virtualservice
spec:
  hosts:
  - cms-svc.btv-backing.svc.cluster.local # service name to call
  http:
  - match:
    - headers:
        membership:
          exact: vip
    route:
    - destination:
        host: cms-svc.btv-backing.svc.cluster.local 
        subset: v2
  - route:
    - destination:
        host: cms-svc.btv-backing.svc.cluster.local # service name to call
        subset: v1 # name for subset name