apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cms-svc # just name for resource
spec:
  host: cms-svc.btv-backing.svc.cluster.local # service name. add full fqdn if outside of namespace
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 100
  subsets:
  - name: v1 # subset name virtual service call in destination.subset
    labels:
      version: v1 # label of deployment.template.labels
  - name: v2 # subset name virtual service call in destination.subset
    labels:
      version: v2 # label of deployment.template.labels